### ISSUE TITLE
The build is broken.

### ISSUE THREAD

**Issue by sizov2405** [pingunaut/haveibeenpwned4j#3]
Hi Martin. It seems to me that the build at the maven central is broken. I used your maven dependency 
<dependency>
  <groupId>de.martinspielmann.haveibeenpwned4j</groupId>
  <artifactId>haveibeenpwned4j</artifactId>
  <version>1.0.0</version>
</dependency>

 and tried to compile my project. This is what I got:

    [javac] /Users/alexandrsizov/MYPROJECTS/DS/ds-mngr/src/java/com/modirum/ds/mngr/controller/PasswordChangeController.java:21: error: cannot access HaveIBeenPwnedApiClient
    [javac] import de.martinspielmann.haveibeenpwned4j.HaveIBeenPwnedApiClient;
    [javac]                                           ^
    [javac]   bad class file: /Users/alexandrsizov/MYPROJECTS/DS/ds-mngr/target/lib/haveibeenpwned4j-1.0.0.jar(de/martinspielmann/haveibeenpwned4j/HaveIBeenPwnedApiClient.class)
    [javac]     class file has wrong version 55.0, should be 52.0
    [javac]     Please remove or make sure it appears in the correct subdirectory of the classpath.

Same happens with version 1.1.0

Could you please advise? 

Thank you,
Alex

**Comment by martinspielmann** [comment]
Hi @sizov2405 
to use this library Java 11 is required. You are trying with Java 8.
