### ISSUE TITLE
Cool Project, has this ever been built into a website?

### ISSUE THREAD

**Issue by southeasterntech** [pingunaut/haveibeenpwned4j#9]
HI Martin,

Do you have any ideas on building this into a functioning website?  Any examples?

Thanks 
Shane

**Comment by martinspielmann** [comment]
Hi Shane,

sure. Clearly depends on the framework you use, but a minimal example is the following.
```
try {
  boolean isPwned = new HaveIBeenPwnedApiClient().isPasswordPwned(password);
  if(isPwned){
    // handle
  }
} catch (HaveIBeenPwnedException e) {
  // handle
}
```

An ready-to-use password validator, in this case for projects using [Apache Wicket](https://github.com/apache/wicket) can be found here:
https://github.com/martinspielmann/wicket-pwnedpasswords-validator/blob/master/src/main/java/de/martinspielmann/wicket/pwnedpasswordsvalidator/PwnedPasswordsValidator.java

Does that help?

**Comment by martinspielmann** [comment]
Ah I realised maybe I got the question wrong. haveibeenpwned4j has been used by myself a lot, however, not projects that are reachable from the public Internet. If it is in use by others? - I cannot tell as there's no tracking whatsoever included.

**Comment by southeasterntech** [comment]
Martin, thanks so much for the response.... really appreciate it.   

 

We're basically ending our contract with DarkWebID and I've been looking for an alternate way of doing searching the Dark Web for this information.  That's where I came across your code.  While I'm a pretty decent Admin, on Linux webservers and such dev stuff is a personal limitation, our in-house dev girl is too busy to even talk to me about this project (not her priority..).   

 

What would be the most straightforward way to produce something do you think?  Looks like your wicket example would get something up and running quick, but whole domain searches would be what we're hoping for, at least.  Curious why you didn't put this more advanced code into Wicket?

 

My ultimate goal would be to get your Ultimate Java code into a basic website so our techs can run searches there.... on a branded site, then just print the results and send to clients...

 

Your advice much respected and appreciated...

 

 












	
		
			
			
			
			
			
				
					
						Shane D. Lewis
					
					
						Technical Director
					
					
						
						
							
								
									Website: www.setechnical.net
								
								
									***@***.***
								
								
									Phone: 6788076156 x 701
								
							
						
						
					
					
						
						
							
								
									
									
									
								
							
						
						
					
				
			
			
		
	



	
		
			
		
	












 

 

----- Original message -----

**Comment by southeasterntech** [comment]
If I'm tracking you correctly, yes... I could just use haveibeenpwned.com, but I'm trying to avoid slipstreaming the results into a new document... but rather have a website that we host internally, and query HIBP via API, to generate the form (website) response and then have the tech print the page for domain.com, and have the branded results already client-ready, if that makes sense.

 












	
		
			
			
			
			
			
				
					
						Shane D. Lewis
					
					
						Technical Director
					
					
						
						
							
								
									Website: www.setechnical.net
								
								
									***@***.***
								
								
									Phone: 6788076156 x 701
								
							
						
						
					
					
						
						
							
								
									
									
									
								
							
						
						
					
				
			
			
		
	



	
		
			
		
	












 

 

----- Original message -----

**Comment by martinspielmann** [comment]
This project is a Java wrapper for HIBP. It can be used in web applications. However, this should be implemented in an own project to keep this dependency as small and focused as possible. 
if you choose this library as a backend for you web app, do not hesitate to create an issue or PR in case you hit any limitations
